- name: Install basic packages
  tags: centos_basic
  yum:
    name:
      - firewalld
      - vim-enhanced
      - git
      - wget
      - curl
      - nmap
      - rsync
      - traceroute
      - ntp
      - net-tools
      - unzip
    update_cache: true
    state: latest
  register: result